# test2 docker-compose
version: "2"
services:
  # There is only one test instance of light-reference and it is allocated at test2
  reference:
    image: networknt/com.networknt.reference-1.0.0:latest
    volumes:
      - ./test2/reference:/config
    environment:
      - STATUS_HOST_IP=${DOCKER_HOST_IP}
    network_mode: host
