version: "2"
#
# Services
#
services:
   hybrid-service:
      build: ./hybrid-services/
      volumes:
        - ./hybrid-services/config:/config
        - ./hybrid-services/service:/service
      ports:
        - 8443:8443
      networks:
          - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true