version: '2'

services:

  oauth2:
    build: oauth2/
    ports:
      - "8888:8888"
    networks:
      - light

  influxdb:
    build: influxdb/
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - light

  grafana:
    build: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    networks:
      - light

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - light
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - light
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - light

networks:
  light:
    driver: bridge
