version: "2"
#
# Services
#
services:
   cdcserver:
      image: networknt/eventuate-cdcserver
      volumes:
        - ./cdc-server/config:/config
      networks:
        - localnet

# Networks
#
networks:
  localnet:
    external: true
    