version: "2"
#
# Services
#
services:


   mysql:
       build: ./mysql/
       ports:
           - 3306:3306
       environment:
           - MYSQL_ROOT_PASSWORD=rootpassword
           - MYSQL_USER=mysqluser
           - MYSQL_PASSWORD=mysqlpw
       networks:
           - localnet

   hybrid-service:
      build: ./hybrid-services/
      volumes:
        - ./hybrid-services/config:/config
        - ./hybrid-services/service:/service
      ports:
        - 8443:8443
      links:
          - mysql
      networks:
          - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true