version: '2'
services:
  mysql:
    image: networknt/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    network_mode: "host"
  redis:
    image: redis
    ports:
      - 6379:6379
    network_mode: "host"
