# Zookeeper and Kafka for local development
version: "2"
services:
  zookeeper:
    image: networknt/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
    networks:
      - localnet
  kafka:
    image: networknt/kafka:latest
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    external: true
