version: "2"
#
# Services
#
services:
  local-eventuate-cdcserver:
    build: ./eventuate-mariadb-cdcserver
    volumes:
      - ./eventuate-mariadb-cdcserver/config:/config
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    external: true
