version: "3.5"

services:
 machinery:
  image: kerberos/machinery
  ports:
   - "8889:8889"
  volumes:
   - kerberos-config:/etc/opt/kerberosio/config
   - kerberos-capture:/etc/opt/kerberosio/capture
   - kerberos-logs:/etc/opt/kerberosio/logs

 web:
  image: kerberos/web
  environment:
   - KERBEROSIO_SECURE_SSL=false
  ports:
   - "8080:80"
  volumes:
   - kerberos-config:/etc/opt/kerberosio/config
   - kerberos-capture:/etc/opt/kerberosio/capture
   - kerberos-logs:/etc/opt/kerberosio/logs

volumes:
 kerberos-config:
 kerberos-capture:
 kerberos-logs:

# Networks
#
networks:
 localnet:
  external: true
