version: "2"
#
# Services
#
services:
  local-tram-cdcserver:
    build: ./tram-cdcserver
    volumes:
      - ./tram-cdcserver/config:/config
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    external: true
