version: '2'

services:

  prometheus:
    build: ./prometheus/
    networks:
      - localnet
    ports:
    - 9090:9090


  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - "3000:3000"
    links:
      - prometheus
    networks:
      - localnet

#
# Networks
#
networks:
    localnet:
        # driver: bridge
        external: true
