  version: '2'
  services:
    sqlserver:
      image: microsoft/mssql-server-linux:2017-latest
      volumes:
        - ./sqlserver:/usr/src/app
      working_dir: /usr/src/app
      # run the entrypoint.sh that will import the data AND sqlserver
      command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
      environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: StrongPassw0rd
        MSSQL_PID: Developer
      ports:
        - '1433:1433'
      networks:
        - localnet

    oauth2-code:
      image: networknt/oauth2-code:2.0.19
      ports:
        - "6881:6881"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-code:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-code"
      #    env: "dev"
    oauth2-token:
      image: networknt/oauth2-token:2.0.19
      ports:
        - "6882:6882"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-token:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    oauth2-service:
      image: networknt/oauth2-service:2.0.19
      ports:
        - "6883:6883"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-service:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    oauth2-client:
      image: networknt/oauth2-client:2.0.19
      ports:
        - "6884:6884"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-client:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-client"
      #    env: "dev"
    oauth2-user:
      image: networknt/oauth2-user:2.0.19
      ports:
        - "6885:6885"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-user:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-user"
      #    env: "dev"
    oauth2-key:
      image: networknt/oauth2-key:2.0.19
      ports:
        - "6886:6886"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-key:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-key"
      #    env: "dev"
    oauth2-refresh-token:
      image: networknt/oauth2-refresh-token:2.0.19
      ports:
        - "6887:6887"
      volumes:
        - ./light-oauth2/sqlserver/config/oauth2-refresh-token:/config
      networks:
        - localnet
      depends_on:
        - sqlserver
      links:
        - sqlserver
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-refresh-token"
      #    env: "dev"

  networks:
    localnet:
      external: true
