version: "2"
#
# Services
#
services:
  mysql:
    image: networknt/mysql
    restart: always
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - localnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 8080:80
    links:
      - mysql
    networks:
      - localnet

  arango:
    image: arangodb/arangodb:latest
    restart: always
    volumes:
      - /opt/arangodb3:/var/lib/arangodb3
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    networks:
      - localnet

  influxdb:
    image: influxdb:1.3-alpine
    restart: always
    volumes:
      - /opt/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_USER=metrics
      - INFLUXDB_USER_PASSWORD=secret
      - INFLUXDB_DB=metrics
    networks:
      - localnet

  chronograf:
    image: chronograf:1.3-alpine
    restart: always
    volumes:
      - /opt/chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    links:
      - influxdb
    networks:
      - localnet

  redis:
    image: redis:4.0-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - /opt/redis/db:/data
    ports:
      - 6379:6379
    networks:
      - localnet

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - /opt/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - localnet

  elasticsearch:
    build: elasticsearch/
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - localnet
  logstash:
    build: logstash/
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - 5000:5000
    networks:
      - localnet
  kibana:
    build: kibana/
    restart: always
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - 5601:5601
    networks:
      - localnet

  zookeeper:
    image: networknt/zookeeper:latest
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
    networks:
      - localnet

  kafka:
    image: networknt/kafka:latest
    restart: always
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181
    networks:
      - localnet

  consul:
    image:  gliderlabs/consul:latest
    restart: always
    command: "agent -server -data-dir /tmp/consul -bootstrap -ui -client=0.0.0.0"
    ports:
      - 8500:8500
      - 8400:8400

  cdcserver-eventuate:
    image: networknt/eventuate-cdcserver:latest
    restart: always
    volumes:
      - ./eventuate-cdcserver/config:/config
    networks:
      - localnet

  cdcserver-tram:
    image: networknt/tram-cdcserver:latest
    restart: always
    volumes:
      - ./tram-cdcserver/config:/config
    networks:
      - localnet

  oauth2-code:
    image: networknt/oauth2-code
    restart: always
    ports:
      - "6881:6881"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-code:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-code"
    #    env: "dev"
  oauth2-token:
    image: networknt/oauth2-token
    restart: always
    ports:
      - "6882:6882"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-token:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-token"
    #    env: "dev"
  oauth2-service:
    image: networknt/oauth2-service
    restart: always
    ports:
      - "6883:6883"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-service:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-service"
    #    env: "dev"
  oauth2-client:
    image: networknt/oauth2-client
    restart: always
    ports:
      - "6884:6884"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-client:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-client"
    #    env: "dev"
  oauth2-user:
    image: networknt/oauth2-user
    restart: always
    ports:
      - "6885:6885"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-user:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-user"
    #    env: "dev"
  oauth2-key:
    image: networknt/oauth2-key
    restart: always
    ports:
      - "6886:6886"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-key:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-key"
    #    env: "dev"
  oauth2-refresh-token:
    image: networknt/oauth2-refresh-token
    restart: always
    ports:
      - "6887:6887"
    volumes:
      - ./light-oauth2/mysql/config/oauth2-refresh-token:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-refresh-token"
    #    env: "dev"

  tokenization:
    image: networknt/tokenization-1.0.0
    restart: always
    ports:
      - "6888:6888"
    volumes:
      - ./tokenization:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql

# Networks
#
networks:
  localnet:
    external: true

