version: "2"
#
# Services
#
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=38.113.162.53:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    networks:
      - localnet

  light-proxy:
    image: networknt/light-proxy:latest
    ports:
      - 8080:8080
    volumes:
      - ./light-proxy/schema-registry:/config
    links:
      - schema-registry
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    external: true
