version: '2'

#
# Services
#
services:

  influxdb:
    build: influxdb/
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - localnet

  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - "3000:3000"
    links:
      - influxdb
    networks:
      - localnet

#
# Networks
#
networks:
    localnet:
        external: true