version: "2"
#
# Services
#
services:
  mariadb:
       build: ./mariadb/
       ports:
           - 3306:3306
       environment:
           - MYSQL_ROOT_PASSWORD=rootpassword
           - MYSQL_USER=mysqluser
           - MYSQL_PASSWORD=mysqlpw
       networks:
           - localnet



# Networks
#
networks:
  localnet:
    external: true
