version: "2.0"
services:

  tokenization:
    image: networknt/tokenization-1.0.0
    ports:
      - "6888:6888"
    volumes:
      - ./tokenization:/config
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    external: true
