  version: '2'
  services:
    sqlserver:
      image: microsoft/mssql-server-linux:2017-latest
      volumes:
        - ./sqlserver:/usr/src/app
      working_dir: /usr/src/app
      # run the entrypoint.sh that will import the data AND sqlserver
      command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
      environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: StrongPassw0rd
        MSSQL_PID: Developer
      ports:
        - '1433:1433'