version: "2"
#
# Services
#
services:
   hybrid-command:
      build: ./eventuate/hybrid-command/
      volumes:
        - ./eventuate/hybrid-command/config:/config
        - ./eventuate/hybrid-command/service:/service
      ports:
        - 8083:8083
      networks:
          - localnet

   hybrid-query:
      build: ./eventuate/hybrid-query/
      volumes:
        - ./eventuate/hybrid-query/config:/config
        - ./eventuate/hybrid-query/service:/service
      ports:
        - 8082:8082
      networks:
          - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true