version: '2'

#
# Services
#
services:

  influxdb:
    image: influxdb:1.5-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_DB=metrics
    networks:
      - localnet
  
  chronograf:
    image: chronograf:1.5-alpine
    ports:
      - "8888:8888"
    links:
      - influxdb
    networks:
      - localnet

  kapacitor:
    image: kapacitor:1.5-alpine
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
    networks:
      - localnet

  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - "3000:3000"
    links:
      - influxdb
    networks:
      - localnet

#
# Networks
#
networks:
    localnet:
        external: true