---
dbType: mysql
jdbcUrl: jdbc:mariadb://mariadb:3306/eventuate?useSSL=false
dbHost: mariadb
dbPort: 3306
dbUser: root
dbPass: rootpassword
dbName: eventuate
dbHistoryTopicName: db.history.topic
sourceTableName: EVENTS
maximumPoolSize: 10
kafka: kafka:9092
zookeeper: zookeeper:2181
leadershipLockPath: /eventuatelocal/cdc/leader
mySqlBinLogClientName: MySqlBinLog
oldDbHistoryTopicName: eventuate.local.cdc.my-sql-connector.offset.storage
